name: Build (targets)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [esp32, esp32s2, esp32s3, esp32c3, esp32c6]
        example: [basic_ranging, ultra_low_power]

    steps:
      - uses: actions/checkout@v4

      - name: Build example (in ESP-IDF container)
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.2
          command: |
            cd examples/${{ matrix.example }}
            idf.py set-target ${{ matrix.target }}
            idf.py build

